import { reactive, watch } from 'vue'

const STORAGE_KEY = 'i_doms_function_params'

export const SALARY_PUSH_MODES = {
  ON_REPORT: 'on_report',
  ON_AUDIT: 'on_audit',
  MANUAL: 'manual',
}

export const SALARY_PUSH_OPTIONS = [
  { value: SALARY_PUSH_MODES.ON_REPORT, label: '报工即推送' },
  { value: SALARY_PUSH_MODES.ON_AUDIT, label: '审核后推送' },
  { value: SALARY_PUSH_MODES.MANUAL, label: '手动推送' },
]

export const SALARY_PUSH_DESCRIPTION =
  '报工即推送：报工即展示在工时工资列表中，工人可查看。审核后推送：审核通过后展示在工时工资列表中，工人可查看。手动推送：手动操作推送后，工人在工时工资列表中可查看。'

export const AUTO_GENERATE_DOC_TYPES = {
  PURCHASE_REQUISITION: 'purchaseRequisition',
  OUTSOURCING_ORDER: 'outsourcingOrder',
  PRODUCTION_WORK_ORDER: 'productionWorkOrder',
  ASSEMBLY_WORK_ORDER: 'assemblyWorkOrder',
}

export const AUTO_GENERATE_DOC_OPTIONS = [
  { value: AUTO_GENERATE_DOC_TYPES.PURCHASE_REQUISITION, label: '采购申请单' },
  { value: AUTO_GENERATE_DOC_TYPES.OUTSOURCING_ORDER, label: '外协订单' },
  { value: AUTO_GENERATE_DOC_TYPES.PRODUCTION_WORK_ORDER, label: '生产工单' },
  { value: AUTO_GENERATE_DOC_TYPES.ASSEMBLY_WORK_ORDER, label: '总装/部装工单' },
]

export const AUTO_GENERATE_DOC_DESCRIPTION =
  '勾选相应单据，销售订单审核后，系统将根据物料的供应型态自动生成相应单据。'

export const INVENTORY_DEDUCT_MODES = {
  NO_ISSUE: 'no_issue',
  POST_COMPLETE_BY_REPORT: 'post_complete_by_report',
  SELF_ISSUE_BY_ACTUAL: 'self_issue_by_actual',
}

export const INVENTORY_DEDUCT_OPTIONS = [
  { value: INVENTORY_DEDUCT_MODES.NO_ISSUE, label: '不领料' },
  {
    value: INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT,
    label: '完工后预扣+确认（按报工数量扣）',
  },
  {
    value: INVENTORY_DEDUCT_MODES.SELF_ISSUE_BY_ACTUAL,
    label: '自主领料+完工后预扣+确认（按领料数量扣）',
  },
]

export const INVENTORY_DEDUCT_DESCRIPTION =
  '不领料：生产过程不扣减库存。完工后预扣+确认（按报工数量扣）：完工时按报工数量预扣，确认后正式扣减。自主领料+完工后预扣+确认（按领料数量扣）：支持自主领料，完工后按领料数量预扣，确认后正式扣减。'

/** 出库规则：双物料单位批次匹配顺序（命名含规划中的整批/余料优先） */
export const OUTBOUND_ISSUE_RULES = {
  FIFO: 'fifo',
  LIFO: 'lifo',
  MANUAL: 'manual',
}

export const OUTBOUND_ISSUE_RULE_OPTIONS = [
  { value: OUTBOUND_ISSUE_RULES.FIFO, label: '先进先出+优先整批+余料优先', disabled: false },
  {
    value: OUTBOUND_ISSUE_RULES.LIFO,
    label: '后进先出+优先整批+余料优先',
    disabled: true,
  },
  { value: OUTBOUND_ISSUE_RULES.MANUAL, label: '自主拣选', disabled: true },
]

export const OUTBOUND_ISSUE_RULE_DESCRIPTION =
  '本期仅开放「先进先出+优先整批+余料优先」：填写出库数量后，确认出库时按以下顺序自动匹配——①优先找单批/单件长度≥需求（整根/整批满足）；②候选中余料优先、其次最短够用；③同条件再按批次号先进先出。仅当没有单根/单批够用时，才允许跨批硬凑。「后进先出」「自主拣选」本期置灰未开放。'

/**
 * 双单位发料规则（管材/板材共用；单单位默认走部分出）
 * - partial：部分出+余料留原批
 * - whole_with_remnant：整批出+余料确认回库
 */
export const DUAL_UNIT_ISSUE_STRATEGIES = {
  PARTIAL: 'partial',
  WHOLE_WITH_REMNANT: 'whole_with_remnant',
}

export const DUAL_UNIT_ISSUE_STRATEGY_OPTIONS = [
  {
    value: DUAL_UNIT_ISSUE_STRATEGIES.WHOLE_WITH_REMNANT,
    label: '整批出+余料确认回库',
    disabled: false,
  },
  { value: DUAL_UNIT_ISSUE_STRATEGIES.PARTIAL, label: '部分出+余料留原批', disabled: false },
]

export const DUAL_UNIT_ISSUE_STRATEGY_DESCRIPTION =
  '单单位物料默认发料规则为部分出+余料留原批。' +
  '双单位部分出+余料留原批：确认出库按需求数量扣减；一批一码/一类一码余量留在原批次；一物一码将大于需求的整件核销后，余量自动生成余料件码挂原父批。' +
  '双单位整批出+余料确认回库：确认出库按整批/整件离开发料仓，实发可大于需求；' +
  '须在「下料结算」填写实耗并确认回库：余料建新批次号、标识为余料，血缘挂原批，默认回发料仓。'

export const AUTO_APPROVE_TYPES = {
  PURCHASE_ORDER: 'purchaseOrder',
  SALES_ORDER: 'salesOrder',
  SALES_ORDER_PRICE_CHANGE: 'salesOrderPriceChange',
  OUTSOURCING_ORDER: 'outsourcingOrder',
  FINISHED_INBOUND: 'finishedInbound',
  MATERIAL_REQUISITION: 'materialRequisition',
  INVENTORY_DEDUCT: 'inventoryDeduct',
}

export const AUTO_APPROVE_OPTIONS = [
  { value: AUTO_APPROVE_TYPES.PURCHASE_ORDER, label: '采购订单' },
  { value: AUTO_APPROVE_TYPES.SALES_ORDER, label: '销售订单' },
  { value: AUTO_APPROVE_TYPES.SALES_ORDER_PRICE_CHANGE, label: '销售订单价格变更' },
  { value: AUTO_APPROVE_TYPES.OUTSOURCING_ORDER, label: '外协订单' },
  { value: AUTO_APPROVE_TYPES.FINISHED_INBOUND, label: '成品入库' },
  { value: AUTO_APPROVE_TYPES.MATERIAL_REQUISITION, label: '领料申请' },
  { value: AUTO_APPROVE_TYPES.INVENTORY_DEDUCT, label: '库存扣减' },
]

export const AUTO_APPROVE_DESCRIPTION =
  '勾选后对应单据提交即自动审批通过。勾选「销售订单价格变更」后，价格变更单提交即回写订单有效价。未勾选「领料申请」时，领料申请单需人工审核（待审核 → 审核通过 / 审核驳回）。未勾选「库存扣减」时，待确认扣减需人工确认（编辑 / 确认 / 作废）；勾选后提交即自动确认扣减。'

function createDefaultAutoGenerateDocs() {
  return {
    [AUTO_GENERATE_DOC_TYPES.PURCHASE_REQUISITION]: false,
    [AUTO_GENERATE_DOC_TYPES.OUTSOURCING_ORDER]: false,
    [AUTO_GENERATE_DOC_TYPES.PRODUCTION_WORK_ORDER]: false,
    [AUTO_GENERATE_DOC_TYPES.ASSEMBLY_WORK_ORDER]: false,
  }
}

function normalizeAutoGenerateDocs(value) {
  const defaults = createDefaultAutoGenerateDocs()
  if (!value || typeof value !== 'object') return defaults
  return {
    ...defaults,
    ...Object.fromEntries(
      AUTO_GENERATE_DOC_OPTIONS.map((item) => [item.value, Boolean(value[item.value])]),
    ),
  }
}

function createDefaultAutoApproveDocs() {
  return {
    [AUTO_APPROVE_TYPES.PURCHASE_ORDER]: false,
    [AUTO_APPROVE_TYPES.SALES_ORDER]: false,
    [AUTO_APPROVE_TYPES.SALES_ORDER_PRICE_CHANGE]: false,
    [AUTO_APPROVE_TYPES.OUTSOURCING_ORDER]: false,
    [AUTO_APPROVE_TYPES.FINISHED_INBOUND]: false,
    [AUTO_APPROVE_TYPES.MATERIAL_REQUISITION]: false,
    [AUTO_APPROVE_TYPES.INVENTORY_DEDUCT]: false,
  }
}

function normalizeAutoApproveDocs(value) {
  const defaults = createDefaultAutoApproveDocs()
  if (!value || typeof value !== 'object') return defaults
  return {
    ...defaults,
    ...Object.fromEntries(
      AUTO_APPROVE_OPTIONS.map((item) => [item.value, Boolean(value[item.value])]),
    ),
  }
}

export const FUNCTION_PARAM_ROWS = [
  {
    key: 'salaryPushMode',
    scenario: '工资推送',
    description: SALARY_PUSH_DESCRIPTION,
  },
  {
    key: 'autoGenerateDocs',
    scenario: '自动生成单据',
    description: AUTO_GENERATE_DOC_DESCRIPTION,
  },
  {
    key: 'autoApproveDocs',
    scenario: '自动审批配置',
    description: AUTO_APPROVE_DESCRIPTION,
  },
  {
    key: 'inventoryDeductMode',
    scenario: '库存扣减',
    description: INVENTORY_DEDUCT_DESCRIPTION,
  },
  {
    key: 'outboundIssueRule',
    scenario: '出库规则',
    description: OUTBOUND_ISSUE_RULE_DESCRIPTION,
  },
  {
    key: 'dualUnitIssueStrategy',
    scenario: '双单位发料规则',
    description: DUAL_UNIT_ISSUE_STRATEGY_DESCRIPTION,
  },
]

function normalizeSalaryPushMode(mode) {
  if (mode === 'auto') return SALARY_PUSH_MODES.ON_REPORT
  if (SALARY_PUSH_OPTIONS.some((item) => item.value === mode)) return mode
  return SALARY_PUSH_MODES.MANUAL
}

function normalizeInventoryDeductMode(mode) {
  // 兼容旧值「按计划数量扣」
  if (mode === 'post_complete_by_plan') return INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
  if (INVENTORY_DEDUCT_OPTIONS.some((item) => item.value === mode)) return mode
  return INVENTORY_DEDUCT_MODES.NO_ISSUE
}

function normalizeOutboundIssueRule(mode) {
  const hit = OUTBOUND_ISSUE_RULE_OPTIONS.find((item) => item.value === mode)
  // 本期仅开放 FIFO；历史 LIFO/自主拣选回落为先进先出
  if (hit && !hit.disabled) return hit.value
  return OUTBOUND_ISSUE_RULES.FIFO
}

function normalizeDualUnitIssueStrategy(mode) {
  if (DUAL_UNIT_ISSUE_STRATEGY_OPTIONS.some((item) => item.value === mode && !item.disabled)) {
    return mode
  }
  return DUAL_UNIT_ISSUE_STRATEGIES.PARTIAL
}

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      if (parsed && typeof parsed === 'object') {
        return {
          ...parsed,
          salaryPushMode: normalizeSalaryPushMode(parsed.salaryPushMode),
          autoGenerateDocs: normalizeAutoGenerateDocs(parsed.autoGenerateDocs),
          autoApproveDocs: normalizeAutoApproveDocs(parsed.autoApproveDocs),
          inventoryDeductMode: normalizeInventoryDeductMode(parsed.inventoryDeductMode),
          outboundIssueRule: normalizeOutboundIssueRule(parsed.outboundIssueRule),
          dualUnitIssueStrategy: normalizeDualUnitIssueStrategy(parsed.dualUnitIssueStrategy),
        }
      }
    }
  } catch {
    /* ignore */
  }
  return null
}

function persist() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(functionParamState.params))
}

export const functionParamState = reactive({
  params: loadFromStorage() || {
    salaryPushMode: SALARY_PUSH_MODES.MANUAL,
    autoGenerateDocs: createDefaultAutoGenerateDocs(),
    autoApproveDocs: createDefaultAutoApproveDocs(),
    inventoryDeductMode: INVENTORY_DEDUCT_MODES.NO_ISSUE,
    outboundIssueRule: OUTBOUND_ISSUE_RULES.FIFO,
    dualUnitIssueStrategy: DUAL_UNIT_ISSUE_STRATEGIES.PARTIAL,
  },
})

watch(
  () => functionParamState.params,
  () => persist(),
  { deep: true },
)

export function getSalaryPushMode() {
  return normalizeSalaryPushMode(functionParamState.params.salaryPushMode)
}

export function setSalaryPushMode(mode) {
  const normalized = normalizeSalaryPushMode(mode)
  const hit = SALARY_PUSH_OPTIONS.find((item) => item.value === normalized)
  if (!hit) return { ok: false, message: '无效的推送方式' }
  functionParamState.params.salaryPushMode = normalized
  return { ok: true }
}

export function isReportSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.ON_REPORT
}

export function isAuditSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.ON_AUDIT
}

export function isManualSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.MANUAL
}

export function getAutoGenerateDocs() {
  return normalizeAutoGenerateDocs(functionParamState.params.autoGenerateDocs)
}

export function setAutoGenerateDocs(enabledKeys = []) {
  const keys = Array.isArray(enabledKeys) ? enabledKeys : []
  functionParamState.params.autoGenerateDocs = normalizeAutoGenerateDocs(
    Object.fromEntries(
      AUTO_GENERATE_DOC_OPTIONS.map((item) => [item.value, keys.includes(item.value)]),
    ),
  )
  return { ok: true }
}

export function isAutoGenerateDocEnabled(type) {
  return Boolean(getAutoGenerateDocs()[type])
}

export function getAutoApproveDocs() {
  return normalizeAutoApproveDocs(functionParamState.params.autoApproveDocs)
}

export function setAutoApproveDocs(enabledKeys = []) {
  const keys = Array.isArray(enabledKeys) ? enabledKeys : []
  functionParamState.params.autoApproveDocs = normalizeAutoApproveDocs(
    Object.fromEntries(AUTO_APPROVE_OPTIONS.map((item) => [item.value, keys.includes(item.value)])),
  )
  return { ok: true }
}

export function isAutoApproveEnabled(type) {
  return Boolean(getAutoApproveDocs()[type])
}

export function getInventoryDeductMode() {
  return normalizeInventoryDeductMode(functionParamState.params.inventoryDeductMode)
}

export function setInventoryDeductMode(mode) {
  const normalized = normalizeInventoryDeductMode(mode)
  const hit = INVENTORY_DEDUCT_OPTIONS.find((item) => item.value === normalized)
  if (!hit) return { ok: false, message: '无效的库存扣减方式' }
  functionParamState.params.inventoryDeductMode = normalized
  return { ok: true }
}

export function isInventoryNoIssue() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.NO_ISSUE
}

export function isInventoryDeductByPlan() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
}

export function isInventoryDeductByReport() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
}

export function isInventoryDeductByActual() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.SELF_ISSUE_BY_ACTUAL
}

export function getOutboundIssueRule() {
  return normalizeOutboundIssueRule(functionParamState.params.outboundIssueRule)
}

export function setOutboundIssueRule(mode) {
  const normalized = normalizeOutboundIssueRule(mode)
  const hit = OUTBOUND_ISSUE_RULE_OPTIONS.find((item) => item.value === normalized)
  if (!hit || hit.disabled) {
    return { ok: false, message: '本期仅开放「先进先出+优先整批+余料优先」' }
  }
  functionParamState.params.outboundIssueRule = normalized
  return { ok: true }
}

export function isManualOutboundIssue() {
  return getOutboundIssueRule() === OUTBOUND_ISSUE_RULES.MANUAL
}

export function isAutoOutboundIssue() {
  const rule = getOutboundIssueRule()
  return rule === OUTBOUND_ISSUE_RULES.FIFO || rule === OUTBOUND_ISSUE_RULES.LIFO
}

export function getDualUnitIssueStrategy() {
  return normalizeDualUnitIssueStrategy(functionParamState.params.dualUnitIssueStrategy)
}

export function setDualUnitIssueStrategy(mode) {
  const normalized = normalizeDualUnitIssueStrategy(mode)
  const hit = DUAL_UNIT_ISSUE_STRATEGY_OPTIONS.find((item) => item.value === normalized)
  if (!hit || hit.disabled) return { ok: false, message: '无效的双单位发料规则' }
  functionParamState.params.dualUnitIssueStrategy = normalized
  return { ok: true }
}

/** 是否按需求数量部分出（双物料单位默认） */
export function isPartialDualUnitIssue() {
  return getDualUnitIssueStrategy() === DUAL_UNIT_ISSUE_STRATEGIES.PARTIAL
}

/** 是否整出+余料回 */
export function isWholeWithRemnantIssue() {
  return getDualUnitIssueStrategy() === DUAL_UNIT_ISSUE_STRATEGIES.WHOLE_WITH_REMNANT
}

/** @deprecated 使用 isReportSalaryPush */
export function isAutoSalaryPush() {
  return isReportSalaryPush()
}
