import { reactive, watch } from 'vue'

const STORAGE_KEY = 'i_doms_function_params'

export const SALARY_PUSH_MODES = {
  ON_REPORT: 'on_report',
  ON_AUDIT: 'on_audit',
  MANUAL: 'manual',
}

export const SALARY_PUSH_OPTIONS = [
  { value: SALARY_PUSH_MODES.ON_REPORT, label: '报工即推送' },
  { value: SALARY_PUSH_MODES.ON_AUDIT, label: '审核后推送' },
  { value: SALARY_PUSH_MODES.MANUAL, label: '手动推送' },
]

export const SALARY_PUSH_DESCRIPTION =
  '报工即推送：报工即展示在工时工资列表中，工人可查看。审核后推送：审核通过后展示在工时工资列表中，工人可查看。手动推送：手动操作推送后，工人在工时工资列表中可查看。'

export const AUTO_GENERATE_DOC_TYPES = {
  PURCHASE_REQUISITION: 'purchaseRequisition',
  OUTSOURCING_ORDER: 'outsourcingOrder',
  PRODUCTION_WORK_ORDER: 'productionWorkOrder',
  ASSEMBLY_WORK_ORDER: 'assemblyWorkOrder',
}

export const AUTO_GENERATE_DOC_OPTIONS = [
  { value: AUTO_GENERATE_DOC_TYPES.PURCHASE_REQUISITION, label: '采购申请单' },
  { value: AUTO_GENERATE_DOC_TYPES.OUTSOURCING_ORDER, label: '外协订单' },
  { value: AUTO_GENERATE_DOC_TYPES.PRODUCTION_WORK_ORDER, label: '生产工单' },
  { value: AUTO_GENERATE_DOC_TYPES.ASSEMBLY_WORK_ORDER, label: '总装/部装工单' },
]

export const AUTO_GENERATE_DOC_DESCRIPTION =
  '勾选相应单据，销售订单审核后，系统将根据物料的供应型态自动生成相应单据。'

export const INVENTORY_DEDUCT_MODES = {
  NO_ISSUE: 'no_issue',
  POST_COMPLETE_BY_REPORT: 'post_complete_by_report',
  SELF_ISSUE_BY_ACTUAL: 'self_issue_by_actual',
}

export const INVENTORY_DEDUCT_OPTIONS = [
  { value: INVENTORY_DEDUCT_MODES.NO_ISSUE, label: '不领料' },
  {
    value: INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT,
    label: '完工后预扣+确认（按报工数量扣）',
  },
  {
    value: INVENTORY_DEDUCT_MODES.SELF_ISSUE_BY_ACTUAL,
    label: '自主领料+完工后预扣+确认（按领料数量扣）',
  },
]

export const INVENTORY_DEDUCT_DESCRIPTION =
  '不领料：生产过程不扣减库存。完工后预扣+确认（按报工数量扣）：完工时按报工数量预扣，确认后正式扣减。自主领料+完工后预扣+确认（按领料数量扣）：支持自主领料，完工后按领料数量预扣，确认后正式扣减。'

export const AUTO_APPROVE_TYPES = {
  PURCHASE_ORDER: 'purchaseOrder',
  SALES_ORDER: 'salesOrder',
  OUTSOURCING_ORDER: 'outsourcingOrder',
  FINISHED_INBOUND: 'finishedInbound',
  MATERIAL_REQUISITION: 'materialRequisition',
  INVENTORY_DEDUCT: 'inventoryDeduct',
}

export const AUTO_APPROVE_OPTIONS = [
  { value: AUTO_APPROVE_TYPES.PURCHASE_ORDER, label: '采购订单' },
  { value: AUTO_APPROVE_TYPES.SALES_ORDER, label: '销售订单' },
  { value: AUTO_APPROVE_TYPES.OUTSOURCING_ORDER, label: '外协订单' },
  { value: AUTO_APPROVE_TYPES.FINISHED_INBOUND, label: '成品入库' },
  { value: AUTO_APPROVE_TYPES.MATERIAL_REQUISITION, label: '领料申请' },
  { value: AUTO_APPROVE_TYPES.INVENTORY_DEDUCT, label: '库存扣减' },
]

export const AUTO_APPROVE_DESCRIPTION =
  '勾选后对应单据提交即自动审批通过。未勾选「领料申请」时，领料申请单需人工审核（待审核 → 审核通过 / 审核驳回）。未勾选「库存扣减」时，待确认扣减需人工确认（编辑 / 确认 / 作废）；勾选后提交即自动确认扣减。'

function createDefaultAutoGenerateDocs() {
  return {
    [AUTO_GENERATE_DOC_TYPES.PURCHASE_REQUISITION]: false,
    [AUTO_GENERATE_DOC_TYPES.OUTSOURCING_ORDER]: false,
    [AUTO_GENERATE_DOC_TYPES.PRODUCTION_WORK_ORDER]: false,
    [AUTO_GENERATE_DOC_TYPES.ASSEMBLY_WORK_ORDER]: false,
  }
}

function normalizeAutoGenerateDocs(value) {
  const defaults = createDefaultAutoGenerateDocs()
  if (!value || typeof value !== 'object') return defaults
  return {
    ...defaults,
    ...Object.fromEntries(
      AUTO_GENERATE_DOC_OPTIONS.map((item) => [item.value, Boolean(value[item.value])]),
    ),
  }
}

function createDefaultAutoApproveDocs() {
  return {
    [AUTO_APPROVE_TYPES.PURCHASE_ORDER]: false,
    [AUTO_APPROVE_TYPES.SALES_ORDER]: false,
    [AUTO_APPROVE_TYPES.OUTSOURCING_ORDER]: false,
    [AUTO_APPROVE_TYPES.FINISHED_INBOUND]: false,
    [AUTO_APPROVE_TYPES.MATERIAL_REQUISITION]: false,
    [AUTO_APPROVE_TYPES.INVENTORY_DEDUCT]: false,
  }
}

function normalizeAutoApproveDocs(value) {
  const defaults = createDefaultAutoApproveDocs()
  if (!value || typeof value !== 'object') return defaults
  return {
    ...defaults,
    ...Object.fromEntries(
      AUTO_APPROVE_OPTIONS.map((item) => [item.value, Boolean(value[item.value])]),
    ),
  }
}

export const FUNCTION_PARAM_ROWS = [
  {
    key: 'salaryPushMode',
    scenario: '工资推送',
    description: SALARY_PUSH_DESCRIPTION,
  },
  {
    key: 'autoGenerateDocs',
    scenario: '自动生成单据',
    description: AUTO_GENERATE_DOC_DESCRIPTION,
  },
  {
    key: 'autoApproveDocs',
    scenario: '自动审批配置',
    description: AUTO_APPROVE_DESCRIPTION,
  },
  {
    key: 'inventoryDeductMode',
    scenario: '库存扣减',
    description: INVENTORY_DEDUCT_DESCRIPTION,
  },
]

function normalizeSalaryPushMode(mode) {
  if (mode === 'auto') return SALARY_PUSH_MODES.ON_REPORT
  if (SALARY_PUSH_OPTIONS.some((item) => item.value === mode)) return mode
  return SALARY_PUSH_MODES.MANUAL
}

function normalizeInventoryDeductMode(mode) {
  // 兼容旧值「按计划数量扣」
  if (mode === 'post_complete_by_plan') return INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
  if (INVENTORY_DEDUCT_OPTIONS.some((item) => item.value === mode)) return mode
  return INVENTORY_DEDUCT_MODES.NO_ISSUE
}

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      if (parsed && typeof parsed === 'object') {
        return {
          ...parsed,
          salaryPushMode: normalizeSalaryPushMode(parsed.salaryPushMode),
          autoGenerateDocs: normalizeAutoGenerateDocs(parsed.autoGenerateDocs),
          autoApproveDocs: normalizeAutoApproveDocs(parsed.autoApproveDocs),
          inventoryDeductMode: normalizeInventoryDeductMode(parsed.inventoryDeductMode),
        }
      }
    }
  } catch {
    /* ignore */
  }
  return null
}

function persist() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(functionParamState.params))
}

export const functionParamState = reactive({
  params: loadFromStorage() || {
    salaryPushMode: SALARY_PUSH_MODES.MANUAL,
    autoGenerateDocs: createDefaultAutoGenerateDocs(),
    autoApproveDocs: createDefaultAutoApproveDocs(),
    inventoryDeductMode: INVENTORY_DEDUCT_MODES.NO_ISSUE,
  },
})

watch(
  () => functionParamState.params,
  () => persist(),
  { deep: true },
)

export function getSalaryPushMode() {
  return normalizeSalaryPushMode(functionParamState.params.salaryPushMode)
}

export function setSalaryPushMode(mode) {
  const normalized = normalizeSalaryPushMode(mode)
  const hit = SALARY_PUSH_OPTIONS.find((item) => item.value === normalized)
  if (!hit) return { ok: false, message: '无效的推送方式' }
  functionParamState.params.salaryPushMode = normalized
  return { ok: true }
}

export function isReportSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.ON_REPORT
}

export function isAuditSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.ON_AUDIT
}

export function isManualSalaryPush() {
  return getSalaryPushMode() === SALARY_PUSH_MODES.MANUAL
}

export function getAutoGenerateDocs() {
  return normalizeAutoGenerateDocs(functionParamState.params.autoGenerateDocs)
}

export function setAutoGenerateDocs(enabledKeys = []) {
  const keys = Array.isArray(enabledKeys) ? enabledKeys : []
  functionParamState.params.autoGenerateDocs = normalizeAutoGenerateDocs(
    Object.fromEntries(
      AUTO_GENERATE_DOC_OPTIONS.map((item) => [item.value, keys.includes(item.value)]),
    ),
  )
  return { ok: true }
}

export function isAutoGenerateDocEnabled(type) {
  return Boolean(getAutoGenerateDocs()[type])
}

export function getAutoApproveDocs() {
  return normalizeAutoApproveDocs(functionParamState.params.autoApproveDocs)
}

export function setAutoApproveDocs(enabledKeys = []) {
  const keys = Array.isArray(enabledKeys) ? enabledKeys : []
  functionParamState.params.autoApproveDocs = normalizeAutoApproveDocs(
    Object.fromEntries(AUTO_APPROVE_OPTIONS.map((item) => [item.value, keys.includes(item.value)])),
  )
  return { ok: true }
}

export function isAutoApproveEnabled(type) {
  return Boolean(getAutoApproveDocs()[type])
}

export function getInventoryDeductMode() {
  return normalizeInventoryDeductMode(functionParamState.params.inventoryDeductMode)
}

export function setInventoryDeductMode(mode) {
  const normalized = normalizeInventoryDeductMode(mode)
  const hit = INVENTORY_DEDUCT_OPTIONS.find((item) => item.value === normalized)
  if (!hit) return { ok: false, message: '无效的库存扣减方式' }
  functionParamState.params.inventoryDeductMode = normalized
  return { ok: true }
}

export function isInventoryNoIssue() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.NO_ISSUE
}

export function isInventoryDeductByPlan() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
}

export function isInventoryDeductByReport() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.POST_COMPLETE_BY_REPORT
}

export function isInventoryDeductByActual() {
  return getInventoryDeductMode() === INVENTORY_DEDUCT_MODES.SELF_ISSUE_BY_ACTUAL
}

/** @deprecated 使用 isReportSalaryPush */
export function isAutoSalaryPush() {
  return isReportSalaryPush()
}
