/** 各模块「新增」页路由配置（列表 path → 新增 path / 标题 / 组件名） */
export const createPageRegistry = [
  {
    listPath: '/procurement/purchase-req',
    newPath: '/procurement/purchase-req/new',
    title: '新增采购申请',
    name: 'procurement-purchase-req-new',
    view: () => import('@/views/procurement/PurchaseRequisitionCreateView.vue'),
    keepAlive: 'PurchaseRequisitionCreateView',
  },
  {
    listPath: '/procurement/purchase-orders',
    newPath: '/procurement/purchase-orders/new',
    title: '新增采购单',
    name: 'procurement-purchase-orders-new',
    view: () => import('@/views/procurement/PurchaseOrderCreateView.vue'),
    keepAlive: 'PurchaseOrderCreateView',
  },
  {
    listPath: '/sales/orders',
    newPath: '/sales/orders/new',
    title: '新增销售订单',
    name: 'sales-orders-new',
    view: () => import('@/views/sales/SalesOrderCreateView.vue'),
    keepAlive: 'SalesOrderCreateView',
  },
  {
    listPath: '/sales/delivery',
    newPath: '/sales/delivery/new',
    title: '新增发货单',
    name: 'sales-delivery-new',
    view: () => import('@/views/sales/DeliveryCreateView.vue'),
    keepAlive: 'DeliveryCreateView',
  },
  {
    listPath: '/production/work-orders',
    newPath: '/production/work-orders/new',
    title: '新增工单',
    name: 'production-work-orders-new',
    view: () => import('@/views/production/WorkOrderCreateView.vue'),
    keepAlive: 'WorkOrderCreateView',
  },
  {
    listPath: '/production/assembly-work-orders',
    newPath: '/production/assembly-work-orders/new',
    title: '新增总装工单',
    name: 'production-assembly-work-orders-new',
    view: () => import('@/views/production/AssemblyWorkOrderCreateView.vue'),
    keepAlive: 'AssemblyWorkOrderCreateView',
  },
  {
    listPath: '/production/qc-work-orders',
    newPath: '/production/qc-work-orders/new',
    title: '新增质检工单',
    name: 'production-qc-work-orders-new',
    view: () => import('@/views/production/QcWorkOrderCreateView.vue'),
    keepAlive: 'QcWorkOrderCreateView',
  },
  {
    listPath: '/production/disassembly-work-orders',
    newPath: '/production/disassembly-work-orders/new',
    title: '新增拆解工单',
    name: 'production-disassembly-work-orders-new',
    view: () => import('@/views/production/DisassemblyWorkOrderCreateView.vue'),
    keepAlive: 'DisassemblyWorkOrderCreateView',
  },
  {
    listPath: '/planning/design-task',
    newPath: '/planning/design-task/new',
    title: '新增设计任务',
    name: 'planning-design-task-new',
    view: () => import('@/views/planning/DesignTaskCreateView.vue'),
    keepAlive: 'DesignTaskCreateView',
  },
  {
    listPath: '/inventory/inbound',
    newPath: '/inventory/inbound/new',
    title: '新增入库单',
    name: 'inventory-inbound-new',
    view: () => import('@/views/inventory/InboundOrderCreateView.vue'),
    keepAlive: 'InboundOrderCreateView',
  },
  {
    listPath: '/inventory/outbound',
    newPath: '/inventory/outbound/new',
    title: '新增出库单',
    name: 'inventory-outbound-new',
    view: () => import('@/views/inventory/OutboundOrderCreateView.vue'),
    keepAlive: 'OutboundOrderCreateView',
  },
  {
    listPath: '/product-process/products',
    newPath: '/product-process/products/new',
    title: '新增产品',
    name: 'product-process-products-new',
    view: () => import('@/views/product-process/MasterItemCreateView.vue'),
    keepAlive: 'MasterItemCreateView',
  },
  {
    listPath: '/product-process/process-config',
    newPath: '/product-process/process-config/new',
    title: '新增工序',
    name: 'product-process-process-config-new',
    view: () => import('@/views/product-process/ProcessConfigCreateView.vue'),
    keepAlive: 'ProcessConfigCreateView',
  },
  {
    listPath: '/product-process/process-category',
    newPath: '/product-process/process-category/new',
    title: '新增工序分类',
    name: 'product-process-process-category-new',
    view: () => import('@/views/product-process/ProcessCategoryCreateView.vue'),
    keepAlive: 'ProcessCategoryCreateView',
  },
  {
    listPath: '/product-process/routing',
    newPath: '/product-process/routing/new',
    title: '新增工艺路线',
    name: 'product-process-routing-new',
    view: () => import('@/views/product-process/ProcessRouteCreateView.vue'),
    keepAlive: 'ProcessRouteCreateView',
  },
  {
    listPath: '/basic-config/material-grades',
    newPath: '/basic-config/material-grades/new',
    title: '新增材质',
    name: 'basic-config-material-grades-new',
    view: () => import('@/views/basic-config/MaterialGradeCreateView.vue'),
    keepAlive: 'MaterialGradeCreateView',
  },
  {
    listPath: '/basic-config/packaging',
    newPath: '/basic-config/packaging/new',
    title: '新增包装族',
    name: 'basic-config-packaging-new',
    view: () => import('@/views/basic-config/PackagingCreateView.vue'),
    keepAlive: 'PackagingCreateView',
  },
  {
    listPath: '/basic-config/defect-items',
    newPath: '/basic-config/defect-items/new',
    title: '新增不良品项',
    name: 'basic-config-defect-items-new',
    view: () => import('@/views/basic-config/DefectItemCreateView.vue'),
    keepAlive: 'DefectItemCreateView',
  },
  {
    listPath: '/basic-config/warehouses',
    newPath: '/basic-config/warehouses/new',
    title: '新增仓库',
    name: 'basic-config-warehouses-new',
    view: () => import('@/views/basic-config/WarehouseCreateView.vue'),
    keepAlive: 'WarehouseCreateView',
  },
  {
    listPath: '/basic-config/warehouse-categories',
    newPath: '/basic-config/warehouse-categories/new',
    title: '新增仓库分类',
    name: 'basic-config-warehouse-categories-new',
    view: () => import('@/views/basic-config/WarehouseCategoryCreateView.vue'),
    keepAlive: 'WarehouseCategoryCreateView',
  },
  {
    listPath: '/basic-config/employee-groups',
    newPath: '/basic-config/employee-groups/new',
    title: '新增员工组别',
    name: 'basic-config-employee-groups-new',
    view: () => import('@/views/basic-config/EmployeeGroupCreateView.vue'),
    keepAlive: 'EmployeeGroupCreateView',
  },
  {
    listPath: '/basic-config/customers',
    newPath: '/basic-config/customers/new',
    title: '新增客户',
    name: 'basic-config-customers-new',
    view: () => import('@/views/basic-config/customers/CustomerCreateView.vue'),
    keepAlive: 'CustomerCreateView',
  },
  {
    listPath: '/basic-config/suppliers',
    newPath: '/basic-config/suppliers/new',
    title: '新增供应商',
    name: 'basic-config-suppliers-new',
    view: () => import('@/views/basic-config/suppliers/SupplierCreateView.vue'),
    keepAlive: 'SupplierCreateView',
  },
  {
    listPath: '/quality/factory-qc',
    newPath: '/quality/factory-qc/new',
    title: '新增出厂质检',
    name: 'quality-factory-qc-new',
    view: () => import('@/views/quality/FactoryQcCreateView.vue'),
    keepAlive: 'FactoryQcCreateView',
  },
]

export function findCreatePageByListPath(listPath) {
  return createPageRegistry.find((item) => item.listPath === listPath) || null
}

export function findCreatePageByNewPath(newPath) {
  return createPageRegistry.find((item) => item.newPath === newPath) || null
}
