/** 生成采购订单页表格列（宽度按单行表头预留，可拖拽调整） */
export const generatePurchaseOrderColumns = [
  { title: '序号', key: 'index', width: 52, align: 'center', fixed: 'left' },
  {
    title: '物料名称',
    key: 'materialName',
    dataIndex: 'materialName',
    width: 120,
    ellipsis: true,
    fixed: 'left',
    sorter: (a, b) =>
      String(a.materialName || '').localeCompare(String(b.materialName || ''), 'zh-CN'),
  },
  { title: '物料类型', key: 'materialType', dataIndex: 'materialType', width: 90 },
  {
    title: '物料编码',
    key: 'materialCode',
    dataIndex: 'materialCode',
    width: 120,
    sorter: (a, b) =>
      String(a.materialCode || '').localeCompare(String(b.materialCode || ''), 'zh-CN'),
  },
  { title: '型号规格', key: 'specModel', dataIndex: 'specModel', width: 100 },
  { title: '材质', key: 'material', dataIndex: 'material', width: 80 },
  {
    title: '变体属性',
    key: 'variantSummary',
    dataIndex: 'variantSummary',
    width: 140,
    ellipsis: true,
  },
  { title: '需求量', key: 'demandQty', dataIndex: 'demandQty', width: 80, align: 'right' },
  {
    title: '订货尺寸',
    key: 'orderSizeText',
    dataIndex: 'orderSizeText',
    width: 160,
    ellipsis: true,
  },
  { title: '库存数量', key: 'stockQty', dataIndex: 'stockQty', width: 90, align: 'right' },
  { title: '计划采购量', key: 'planPurchaseQty', width: 110, required: true },
  { title: '采购单位', key: 'unit', dataIndex: 'unit', width: 100, required: true },
  { title: '结算单位', key: 'settleUnit', dataIndex: 'settleUnit', width: 80 },
  { title: '预计结算数量', key: 'settleQty', width: 120 },
  { title: '库存预警', key: 'stockAlert', width: 130 },
  { title: '指定供应商', key: 'designatedSupplier', width: 110 },
  { title: '供应商名称', key: 'supplierName', width: 160, required: true },
  { title: '收货仓库', key: 'receivingWarehouse', width: 110 },
  { title: '紧急度', key: 'urgency', width: 90 },
  { title: '不含税单价', key: 'unitPriceExTax', width: 110 },
  { title: '税率(%)', key: 'taxRate', width: 90 },
  { title: '单价（含税）', key: 'unitPriceInTax', width: 110, align: 'right' },
  { title: '总价（不含税）', key: 'totalPriceExTax', width: 120, align: 'right' },
  { title: '总价（含税）', key: 'totalPriceInTax', width: 110, align: 'right' },
  {
    title: '期望到货日期',
    key: 'expectedArrivalDate',
    dataIndex: 'expectedArrivalDate',
    width: 130,
  },
  { title: '交货日期', key: 'deliveryDate', width: 120 },
  { title: '结算类型', key: 'settlementType', width: 120 },
  { title: '收货模式', key: 'receivingMode', width: 100 },
  { title: '供货期/天', key: 'leadTimeDays', width: 100 },
  { title: '采购申请单号', key: 'sourceReqNos', width: 140, ellipsis: true },
  { title: '销售单号', key: 'sourceSalesOrderNos', width: 130, ellipsis: true },
  { title: '备注', key: 'remark', width: 140 },
  { title: '操作', key: 'action', width: 140, align: 'center', fixed: 'right' },
]
