/** 采购单明细列定义（新增/编辑表单） */

export const purchaseOrderFormLineColumns = [
  { title: '序号', key: 'index', width: 56, align: 'center' },
  { title: '产品名称', dataIndex: 'productName', key: 'productName', width: 140, ellipsis: true },
  { title: '产品编号', dataIndex: 'productCode', key: 'productCode', width: 120, ellipsis: true },
  { title: '规格型号', dataIndex: 'specModel', key: 'specModel', width: 110, ellipsis: true },
  { title: '规格属性', dataIndex: 'specAttr', key: 'specAttr', width: 90, ellipsis: true },
  { title: '材质', dataIndex: 'material', key: 'material', width: 80, ellipsis: true },
  {
    title: '变体属性',
    dataIndex: 'variantSummary',
    key: 'variantAttr',
    width: 140,
    ellipsis: true,
  },
  { title: '图号', dataIndex: 'drawingNo', key: 'drawingNo', width: 100, ellipsis: true },
  { title: '库存数量', dataIndex: 'stockQty', key: 'stockQty', width: 90, align: 'right' },
  { title: '采购数量', key: 'purchaseQty', width: 100 },
  { title: '单位', dataIndex: 'unit', key: 'unit', width: 70 },
  { title: '不含税单价', key: 'unitPriceExTax', width: 100 },
  { title: '税率(%)', key: 'taxRate', width: 80 },
  { title: '含税单价', key: 'unitPriceInTax', width: 100 },
  { title: '总价（不含税）', key: 'totalPriceExTax', width: 110, align: 'right' },
  { title: '总价（含税）', key: 'totalPriceInTax', width: 100, align: 'right' },
  { title: '交货日期', key: 'deliveryDate', width: 120 },
  { title: '收货仓库', key: 'receivingWarehouse', width: 110 },
  { title: '备注', key: 'remark', width: 120, ellipsis: true },
  { title: '操作', key: 'actions', width: 110 },
]
