/** 销售订单详情 — 销售明细列（与新增/编辑销售订单明细字段对齐，只读） */
export const salesOrderDetailLineColumns = [
  { key: 'index', title: '序号', width: 56, align: 'center', fixed: 'left' },
  {
    key: 'productName',
    title: '产品名称',
    dataIndex: 'productName',
    width: 140,
    ellipsis: true,
    fixed: 'left',
  },
  {
    key: 'productCode',
    title: '产品编码',
    dataIndex: 'productCode',
    width: 130,
    ellipsis: true,
    fixed: 'left',
  },
  { key: 'businessType', title: '业务类型', width: 110 },
  { key: 'productAttr', title: '产品属性', dataIndex: 'productAttr', width: 90 },
  { key: 'specModel', title: '规格型号', dataIndex: 'specModel', width: 100 },
  { key: 'material', title: '材质', dataIndex: 'material', width: 80 },
  {
    key: 'variantAttr',
    title: '变体属性',
    dataIndex: 'variantSummary',
    width: 160,
    ellipsis: true,
  },
  { key: 'drawingNo', title: '图号', dataIndex: 'drawingNo', width: 100, ellipsis: true },
  { key: 'techParams', title: '技术参数', dataIndex: 'techParams', width: 120, ellipsis: true },
  {
    key: 'matchingRequirements',
    title: '配套要求',
    dataIndex: 'matchingRequirements',
    width: 120,
    ellipsis: true,
  },
  { key: 'salesQty', title: '销售数量', dataIndex: 'salesQty', width: 90, align: 'right' },
  { key: 'deliveryMode', title: '交付方式', width: 100 },
  { key: 'deliveryDate', title: '交货日期', dataIndex: 'deliveryDate', width: 110 },
  { key: 'unit', title: '单位', dataIndex: 'unit', width: 70 },
  { key: 'bomName', title: 'Bom名称', dataIndex: 'bomName', width: 110, ellipsis: true },
  { key: 'bomVersion', title: 'Bom版本', dataIndex: 'bomVersion', width: 90 },
  {
    key: 'unitPriceExTax',
    title: '单价（不含税）',
    dataIndex: 'unitPriceExTax',
    width: 120,
    align: 'right',
  },
  {
    key: 'unitPriceInTax',
    title: '单价（含税）',
    dataIndex: 'unitPriceInTax',
    width: 110,
    align: 'right',
  },
  { key: 'taxRate', title: '税率(%)', dataIndex: 'taxRate', width: 80, align: 'right' },
  {
    key: 'totalPriceExTax',
    title: '总价（不含税）',
    dataIndex: 'totalPriceExTax',
    width: 110,
    align: 'right',
  },
  {
    key: 'totalPriceInTax',
    title: '总价（含税）',
    dataIndex: 'totalPriceInTax',
    width: 100,
    align: 'right',
  },
  {
    key: 'lineDiscountRate',
    title: '行折扣(%)',
    dataIndex: 'lineDiscountRate',
    width: 90,
    align: 'right',
  },
  {
    key: 'lineDiscountAmount',
    title: '行优惠金额',
    dataIndex: 'lineDiscountAmount',
    width: 100,
    align: 'right',
  },
  { key: 'packagingForm', title: '包装形式', dataIndex: 'packagingForm', width: 90 },
  {
    key: 'supplementDesc',
    title: '补充说明',
    dataIndex: 'supplementDesc',
    width: 100,
    ellipsis: true,
  },
]
