<template>
  <div class="function-param-page">
    <div class="section-head">
      <span class="section-title">参数配置</span>
    </div>

    <div class="table-card">
      <a-table
        :columns="columns"
        :data-source="tableData"
        row-key="key"
        size="small"
        bordered
        :pagination="false"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.key === 'config'">
            <a-radio-group
              v-if="record.key === 'salaryPushMode'"
              :value="salaryPushMode"
              @change="(e) => onSalaryPushChange(e.target.value)"
            >
              <a-radio
                v-for="option in SALARY_PUSH_OPTIONS"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </a-radio>
            </a-radio-group>
            <a-checkbox-group
              v-else-if="record.key === 'autoGenerateDocs'"
              :value="autoGenerateDocKeys"
              @change="onAutoGenerateDocsChange"
            >
              <a-checkbox
                v-for="option in AUTO_GENERATE_DOC_OPTIONS"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </a-checkbox>
            </a-checkbox-group>
            <a-checkbox-group
              v-else-if="record.key === 'autoApproveDocs'"
              class="checkbox-wrap"
              :value="autoApproveDocKeys"
              @change="onAutoApproveDocsChange"
            >
              <a-checkbox
                v-for="option in AUTO_APPROVE_OPTIONS"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </a-checkbox>
            </a-checkbox-group>
            <a-radio-group
              v-else-if="record.key === 'inventoryDeductMode'"
              :value="inventoryDeductMode"
              @change="(e) => onInventoryDeductChange(e.target.value)"
            >
              <a-radio
                v-for="option in INVENTORY_DEDUCT_OPTIONS"
                :key="option.value"
                :value="option.value"
              >
                {{ option.label }}
              </a-radio>
            </a-radio-group>
            <a-radio-group
              v-else-if="record.key === 'outboundIssueRule'"
              :value="outboundIssueRule"
              @change="(e) => onOutboundIssueRuleChange(e.target.value)"
            >
              <a-radio
                v-for="option in OUTBOUND_ISSUE_RULE_OPTIONS"
                :key="option.value"
                :value="option.value"
                :disabled="option.disabled"
              >
                {{ option.label }}
              </a-radio>
            </a-radio-group>
            <a-radio-group
              v-else-if="record.key === 'dualUnitIssueStrategy'"
              :value="dualUnitIssueStrategy"
              @change="(e) => onDualUnitIssueStrategyChange(e.target.value)"
            >
              <a-radio
                v-for="option in DUAL_UNIT_ISSUE_STRATEGY_OPTIONS"
                :key="option.value"
                :value="option.value"
                :disabled="option.disabled"
              >
                {{ option.label }}
              </a-radio>
            </a-radio-group>
            <a-switch
              v-else-if="record.key === 'enablePlateAreaMeasure'"
              :checked="enablePlateAreaMeasure"
              checked-children="开"
              un-checked-children="关"
              @change="onEnablePlateAreaMeasureChange"
            />
            <a-switch
              v-else-if="record.key === 'enableBomWeightCalc'"
              :checked="enableBomWeightCalc"
              checked-children="开"
              un-checked-children="关"
              @change="onEnableBomWeightCalcChange"
            />
            <a-switch
              v-else-if="record.key === 'enableBomLevelMts'"
              :checked="enableBomLevelMts"
              checked-children="开"
              un-checked-children="关"
              @change="onEnableBomLevelMtsChange"
            />
          </template>
          <template v-else-if="column.key === 'description'">
            <span v-if="record.description" class="desc-text">{{ record.description }}</span>
          </template>
        </template>
      </a-table>
    </div>
  </div>
</template>

<script>
export default { name: 'FunctionParamView' }
</script>

<script setup>
import { computed } from 'vue'
import { message } from 'ant-design-vue'
import {
  FUNCTION_PARAM_ROWS,
  SALARY_PUSH_OPTIONS,
  AUTO_GENERATE_DOC_OPTIONS,
  AUTO_APPROVE_OPTIONS,
  INVENTORY_DEDUCT_OPTIONS,
  OUTBOUND_ISSUE_RULE_OPTIONS,
  DUAL_UNIT_ISSUE_STRATEGY_OPTIONS,
  functionParamState,
  setSalaryPushMode,
  setAutoGenerateDocs,
  setAutoApproveDocs,
  setInventoryDeductMode,
  getInventoryDeductMode,
  setOutboundIssueRule,
  getOutboundIssueRule,
  setDualUnitIssueStrategy,
  getDualUnitIssueStrategy,
  isPlateAreaMeasureEnabled,
  setEnablePlateAreaMeasure,
  isBomWeightCalcEnabled,
  setEnableBomWeightCalc,
  isBomLevelMtsEnabled,
  setEnableBomLevelMts,
} from '@/store/functionParamStore'

const columns = [
  { title: '业务场景', dataIndex: 'scenario', key: 'scenario', width: 140 },
  { title: '配置项', key: 'config', width: 760 },
  { title: '说明', key: 'description' },
]

const tableData = FUNCTION_PARAM_ROWS

const salaryPushMode = computed(() => functionParamState.params.salaryPushMode)

const inventoryDeductMode = computed(() => getInventoryDeductMode())
const outboundIssueRule = computed(() => getOutboundIssueRule())
const dualUnitIssueStrategy = computed(() => getDualUnitIssueStrategy())
const enablePlateAreaMeasure = computed(() => isPlateAreaMeasureEnabled())
const enableBomWeightCalc = computed(() => isBomWeightCalcEnabled())
const enableBomLevelMts = computed(() => isBomLevelMtsEnabled())

const autoGenerateDocKeys = computed(() =>
  AUTO_GENERATE_DOC_OPTIONS.filter(
    (option) => functionParamState.params.autoGenerateDocs?.[option.value],
  ).map((option) => option.value),
)

const autoApproveDocKeys = computed(() =>
  AUTO_APPROVE_OPTIONS.filter(
    (option) => functionParamState.params.autoApproveDocs?.[option.value],
  ).map((option) => option.value),
)

function onSalaryPushChange(mode) {
  const res = setSalaryPushMode(mode)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onAutoGenerateDocsChange(keys) {
  const res = setAutoGenerateDocs(keys)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onAutoApproveDocsChange(keys) {
  const res = setAutoApproveDocs(keys)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onInventoryDeductChange(mode) {
  const res = setInventoryDeductMode(mode)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onOutboundIssueRuleChange(mode) {
  const res = setOutboundIssueRule(mode)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onDualUnitIssueStrategyChange(mode) {
  const res = setDualUnitIssueStrategy(mode)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success('已保存')
}

function onEnablePlateAreaMeasureChange(checked) {
  const res = setEnablePlateAreaMeasure(checked)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success(checked ? '已开启面积录入快捷' : '已关闭面积录入快捷（入库直接填库存数量）')
}

function onEnableBomWeightCalcChange(checked) {
  const res = setEnableBomWeightCalc(checked)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success(checked ? '已开启 BOM 重量计算' : '已关闭 BOM 重量计算')
}

function onEnableBomLevelMtsChange(checked) {
  const res = setEnableBomLevelMts(checked)
  if (!res.ok) {
    message.warning(res.message)
    return
  }
  message.success(checked ? '已开启生产计划 BOM 级 MTS' : '已关闭生产计划 BOM 级 MTS')
}
</script>

<style scoped>
.function-param-page {
  padding: 0;
}

.section-head {
  margin-bottom: 12px;
}

.section-title {
  font-size: 16px;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.88);
}

.table-card {
  background: #fff;
  border-radius: 4px;
}

.desc-text {
  color: rgba(0, 0, 0, 0.65);
  line-height: 1.6;
}

.checkbox-wrap {
  display: flex;
  flex-wrap: wrap;
  gap: 4px 8px;
}
</style>
