<template>
  <div class="param-config-cell">
    <a-radio-group
      v-if="record.key === 'salaryPushMode'"
      :value="salaryPushMode"
      @change="(e) => onSalaryPushChange(e.target.value)"
    >
      <a-radio v-for="option in SALARY_PUSH_OPTIONS" :key="option.value" :value="option.value">
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-checkbox-group
      v-else-if="record.key === 'autoGenerateDocs'"
      :value="autoGenerateDocKeys"
      @change="onAutoGenerateDocsChange"
    >
      <a-checkbox
        v-for="option in AUTO_GENERATE_DOC_OPTIONS"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </a-checkbox>
    </a-checkbox-group>

    <a-checkbox-group
      v-else-if="record.key === 'autoApproveDocs'"
      class="checkbox-wrap"
      :value="autoApproveDocKeys"
      @change="onAutoApproveDocsChange"
    >
      <a-checkbox v-for="option in AUTO_APPROVE_OPTIONS" :key="option.value" :value="option.value">
        {{ option.label }}
      </a-checkbox>
    </a-checkbox-group>

    <a-radio-group
      v-else-if="record.key === 'inventoryDeductMode'"
      :value="inventoryDeductMode"
      @change="(e) => onInventoryDeductChange(e.target.value)"
    >
      <a-radio v-for="option in INVENTORY_DEDUCT_OPTIONS" :key="option.value" :value="option.value">
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-radio-group
      v-else-if="record.key === 'outboundIssueRule'"
      :value="outboundIssueRule"
      @change="(e) => onOutboundIssueRuleChange(e.target.value)"
    >
      <a-radio
        v-for="option in OUTBOUND_ISSUE_RULE_OPTIONS"
        :key="option.value"
        :value="option.value"
        :disabled="option.disabled"
      >
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-radio-group
      v-else-if="record.key === 'salesOutboundIssueRule'"
      :value="salesOutboundIssueRule"
      @change="(e) => onSalesOutboundIssueRuleChange(e.target.value)"
    >
      <a-radio
        v-for="option in SALES_OUTBOUND_ISSUE_RULE_OPTIONS"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-radio-group
      v-else-if="record.key === 'shipAttachmentDecideStage'"
      :value="shipAttachmentDecideStage"
      @change="(e) => onShipAttachmentDecideStageChange(e.target.value)"
    >
      <a-radio
        v-for="option in SHIP_ATTACHMENT_DECIDE_STAGE_OPTIONS"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-radio-group
      v-else-if="record.key === 'dualUnitIssueStrategy'"
      :value="dualUnitIssueStrategy"
      @change="(e) => onDualUnitIssueStrategyChange(e.target.value)"
    >
      <a-radio
        v-for="option in DUAL_UNIT_ISSUE_STRATEGY_OPTIONS"
        :key="option.value"
        :value="option.value"
        :disabled="option.disabled"
      >
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-checkbox-group
      v-else-if="record.key === 'blankSizeAssistTools'"
      class="checkbox-wrap"
      :value="blankSizeAssistKeys"
      @change="onBlankSizeAssistChange"
    >
      <a-checkbox
        v-for="option in BLANK_SIZE_ASSIST_OPTIONS"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </a-checkbox>
    </a-checkbox-group>

    <a-switch
      v-else-if="record.key === 'enableBomLevelMts'"
      :checked="enableBomLevelMts"
      checked-children="开"
      un-checked-children="关"
      @change="onEnableBomLevelMtsChange"
    />

    <a-switch
      v-else-if="record.displayOnly && record.controlType === 'switch'"
      :checked="Boolean(displayParams[displaySwitchKey(record)])"
      checked-children="开"
      un-checked-children="关"
      @change="(checked) => onDisplaySwitchChange(record, checked)"
    />

    <a-radio-group
      v-else-if="record.displayOnly && record.controlType === 'radio'"
      :value="displayRadioValue(record)"
      @change="(e) => onDisplayRadioChange(record, e.target.value)"
    >
      <a-radio v-for="option in record.options || []" :key="option.value" :value="option.value">
        {{ option.label }}
      </a-radio>
    </a-radio-group>

    <a-checkbox-group
      v-else-if="record.displayOnly && record.controlType === 'checkboxGroup'"
      class="checkbox-wrap"
      :value="displayCheckboxKeys(record)"
      @change="(keys) => onDisplayCheckboxChange(record, keys)"
    >
      <a-checkbox v-for="option in record.options || []" :key="option.value" :value="option.value">
        {{ option.label }}
      </a-checkbox>
    </a-checkbox-group>

    <div v-else-if="record.key === 'qcGatePolicy'" class="qc-gate-policy">
      <div v-for="scope in QC_GATE_POLICY_BIZ_SCOPES" :key="scope" class="qc-gate-row">
        <span class="qc-gate-scope">{{ scope }}</span>
        <a-radio-group
          :value="qcGatePolicyMap[scope]"
          size="small"
          @change="(e) => onQcGatePolicyChange(scope, e.target.value)"
        >
          <a-radio
            v-for="option in QC_GATE_POLICY_PARAM_OPTIONS"
            :key="option.value"
            :value="option.value"
            :disabled="option.disabled"
          >
            {{ option.label }}
          </a-radio>
        </a-radio-group>
      </div>
    </div>
  </div>
</template>

<script>
export default { name: 'FunctionParamConfigCell' }
</script>

<script setup>
import { computed } from 'vue'
import { message } from 'ant-design-vue'
import {
  SALARY_PUSH_OPTIONS,
  AUTO_GENERATE_DOC_OPTIONS,
  AUTO_APPROVE_OPTIONS,
  INVENTORY_DEDUCT_OPTIONS,
  OUTBOUND_ISSUE_RULE_OPTIONS,
  SALES_OUTBOUND_ISSUE_RULE_OPTIONS,
  SHIP_ATTACHMENT_DECIDE_STAGE_OPTIONS,
  DUAL_UNIT_ISSUE_STRATEGY_OPTIONS,
  BLANK_SIZE_ASSIST_OPTIONS,
  QC_GATE_POLICY_PARAM_OPTIONS,
  QC_GATE_POLICY_BIZ_SCOPES,
  functionParamState,
  setSalaryPushMode,
  setAutoGenerateDocs,
  setAutoApproveDocs,
  setInventoryDeductMode,
  getInventoryDeductMode,
  setOutboundIssueRule,
  getOutboundIssueRule,
  setSalesOutboundIssueRule,
  getSalesOutboundIssueRule,
  setShipAttachmentDecideStage,
  getShipAttachmentDecideStage,
  setDualUnitIssueStrategy,
  getDualUnitIssueStrategy,
  getBlankSizeAssistTools,
  setBlankSizeAssistTools,
  isBomLevelMtsEnabled,
  setEnableBomLevelMts,
  getQcGatePolicyMap,
  setQcGatePolicyByBizScope,
  getDisplayParams,
  setDisplayParam,
} from '@/store/functionParamStore'

defineProps({
  record: { type: Object, required: true },
})

const salaryPushMode = computed(() => functionParamState.params.salaryPushMode)
const inventoryDeductMode = computed(() => getInventoryDeductMode())
const outboundIssueRule = computed(() => getOutboundIssueRule())
const salesOutboundIssueRule = computed(() => getSalesOutboundIssueRule())
const shipAttachmentDecideStage = computed(() => getShipAttachmentDecideStage())
const dualUnitIssueStrategy = computed(() => getDualUnitIssueStrategy())
const enableBomLevelMts = computed(() => isBomLevelMtsEnabled())

const displayParams = computed(() => {
  void functionParamState.params.displayParams
  return getDisplayParams()
})

const qcGatePolicyMap = computed(() => {
  void functionParamState.params.qcGatePolicyByBizScope
  return getQcGatePolicyMap()
})

const autoGenerateDocKeys = computed(() =>
  AUTO_GENERATE_DOC_OPTIONS.filter(
    (option) => functionParamState.params.autoGenerateDocs?.[option.value],
  ).map((option) => option.value),
)

const autoApproveDocKeys = computed(() =>
  AUTO_APPROVE_OPTIONS.filter(
    (option) => functionParamState.params.autoApproveDocs?.[option.value],
  ).map((option) => option.value),
)

const blankSizeAssistKeys = computed(() => {
  void functionParamState.params.blankSizeAssistTools
  const tools = getBlankSizeAssistTools()
  return BLANK_SIZE_ASSIST_OPTIONS.filter((option) => tools[option.value]).map(
    (option) => option.value,
  )
})

function toastSave(res, successText = '已保存') {
  if (!res.ok) {
    message.warning(res.message || '保存失败')
    return
  }
  message.success(successText)
}

function onSalaryPushChange(mode) {
  toastSave(setSalaryPushMode(mode))
}
function onAutoGenerateDocsChange(keys) {
  toastSave(setAutoGenerateDocs(keys))
}
function onAutoApproveDocsChange(keys) {
  toastSave(setAutoApproveDocs(keys))
}
function onInventoryDeductChange(mode) {
  toastSave(setInventoryDeductMode(mode))
}
function onOutboundIssueRuleChange(mode) {
  toastSave(setOutboundIssueRule(mode))
}
function onSalesOutboundIssueRuleChange(mode) {
  toastSave(setSalesOutboundIssueRule(mode))
}
function onShipAttachmentDecideStageChange(mode) {
  toastSave(setShipAttachmentDecideStage(mode))
}
function onDualUnitIssueStrategyChange(mode) {
  toastSave(setDualUnitIssueStrategy(mode))
}
function onBlankSizeAssistChange(keys) {
  toastSave(setBlankSizeAssistTools(keys))
}
function onEnableBomLevelMtsChange(checked) {
  toastSave(
    setEnableBomLevelMts(checked),
    checked ? '已开启生产计划 BOM 级 MTS' : '已关闭生产计划 BOM 级 MTS',
  )
}
function onQcGatePolicyChange(scope, policy) {
  toastSave(setQcGatePolicyByBizScope(scope, policy), `已保存「${scope}」门控配置`)
}

/** 展示项：开关类直接用 row.key 对应 displayParams */
function displaySwitchKey(record) {
  return record.key
}

/** 报工设置等：checkbox 值映射到独立 displayParams 字段 */
function displayCheckboxKeys(record) {
  if (record.key === 'reportSettings') {
    return displayParams.value.reportAllowOverReport ? ['allowOverReport'] : []
  }
  if (record.key === 'workOrderMaterialSettings') {
    const settings = displayParams.value.workOrderMaterialSettings || {}
    return (record.options || []).map((o) => o.value).filter((key) => Boolean(settings[key]))
  }
  return []
}

function onDisplaySwitchChange(record, checked) {
  toastSave(setDisplayParam(record.key, Boolean(checked)))
}

function displayRadioValue(record) {
  if (record.key === 'processFileSelectMode') {
    return displayParams.value.processFileSelectMode || 'item'
  }
  return displayParams.value[record.key]
}

function onDisplayRadioChange(record, value) {
  if (record.key === 'processFileSelectMode') {
    const mode = value === 'category' ? 'category' : 'item'
    toastSave(setDisplayParam('processFileSelectMode', mode))
    setDisplayParam('processFileSelectByCategory', mode === 'category')
    return
  }
  toastSave(setDisplayParam(record.key, value))
}

function onDisplayCheckboxChange(record, keys) {
  const list = Array.isArray(keys) ? keys : []
  if (record.key === 'reportSettings') {
    toastSave(setDisplayParam('reportAllowOverReport', list.includes('allowOverReport')))
    return
  }
  if (record.key === 'workOrderMaterialSettings') {
    const next = {}
    ;(record.options || []).forEach((opt) => {
      next[opt.value] = list.includes(opt.value)
    })
    toastSave(setDisplayParam('workOrderMaterialSettings', next))
    return
  }
  toastSave({ ok: false, message: '未知展示项' })
}
</script>

<style scoped>
.checkbox-wrap {
  display: flex;
  flex-wrap: wrap;
  gap: 4px 12px;
}

.qc-gate-policy {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.qc-gate-row {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.qc-gate-scope {
  flex: 0 0 96px;
  color: rgba(0, 0, 0, 0.85);
  font-size: 13px;
}
</style>
